version: '3.4'

services:
  one-api:
    image: woodchen/czloapi:latest
    container_name: oapi
    restart: always
    command: --log-dir /app/logs
    ports:
      - "6000:3000"
    volumes:
      - /opt/1panel/docker/compose/oapi/data/:/data
      - /opt/1panel/docker/compose/oapi/logs:/app/logs
    environment:
      - SQL_DSN=oapi:rRRaey28iZQRY6GG@tcp(mysql:3306)/oapi  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://default:Node3.14159@redis:6379/6
      - SESSION_SECRET=czloapi  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true