name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: czloapi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: woodchen
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: 构建和推送镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            woodchen/${{ env.IMAGE_NAME }}:latest
            woodchen/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7